# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('facebookId', models.CharField(max_length=200)),
                ('assignedClinician', models.CharField(max_length=200)),
            ],
        ),
    ]
